# Test layer for Solana CLI tests
# Expects cli-local image to be available (built separately or pulled from registry)
ARG BASE_IMAGE=cli-local:latest
FROM ${BASE_IMAGE}

COPY cli/test cli/test
# evm/script needed for the cli, at least for now
COPY evm/script evm/script
COPY solana solana
RUN bash -ci "./cli/test/solana.sh --use-tmp-dir"
