# adapted from https://github.com/metaDAOproject/setup-anchor
name: "Setup Anchor"
description: "Install Anchor, Solana CLI tools, and Node.js."
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: "Version of node.js to use"
    required: true
  solana-cli-version:
    description: "Version of Solana CLI to use"
    required: true
  anchor-version:
    description: "Version of Anchor to use"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Solana CLI tools
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-cli-${{ runner.os }}-build-${{ inputs.solana-cli-version }}
    - name: Install Solana CLI tools
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${INPUTS_SOLANA_CLI_VERSION}/install)"
      shell: bash
      env:
        INPUTS_SOLANA_CLI_VERSION: ${{ inputs.solana-cli-version }}
    - name: Update PATH
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Anchor
      run: bun add -g @coral-xyz/anchor-cli@${INPUTS_ANCHOR_VERSION}
      shell: bash
      env:
        INPUTS_ANCHOR_VERSION: ${{ inputs.anchor-version }}
