[package]
name = "ntt_governance"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
wormhole = { git = "https://github.com/wormholelabs-xyz/wormhole.git", subdir = "sui/wormhole", rev = "de7d526127ee4dfd884c858b315733a825a08db8" }
ntt = { local = "../ntt" }
